import { useAutocompleteFilter, useAutocompleteFilteredItems } from "./autocomplete.hooks"

import {
	AutocompleteRoot,
	AutocompleteInputGroup,
	AutocompleteInput,
	AutocompleteTrigger,
	AutocompleteIcon,
	AutocompleteClear,
	AutocompleteValue,
	AutocompletePortal,
	AutocompleteBackdrop,
	AutocompletePositioner,
	AutocompletePopup,
	AutocompleteArrow,
	AutocompleteStatus,
	AutocompleteEmpty,
	AutocompleteList,
	AutocompleteRow,
	AutocompleteItem,
	AutocompleteSeparator,
	AutocompleteGroup,
	AutocompleteGroupLabel,
	AutocompleteCollection,
} from "./autocomplete"

export const Autocomplete = {
	Root: AutocompleteRoot,
	InputGroup: AutocompleteInputGroup,
	Input: AutocompleteInput,
	Trigger: AutocompleteTrigger,
	Icon: AutocompleteIcon,
	Clear: AutocompleteClear,
	Value: AutocompleteValue,
	Portal: AutocompletePortal,
	Backdrop: AutocompleteBackdrop,
	Positioner: AutocompletePositioner,
	Popup: AutocompletePopup,
	Arrow: AutocompleteArrow,
	Status: AutocompleteStatus,
	Empty: AutocompleteEmpty,
	List: AutocompleteList,
	Row: AutocompleteRow,
	Item: AutocompleteItem,
	Separator: AutocompleteSeparator,
	Group: AutocompleteGroup,
	GroupLabel: AutocompleteGroupLabel,
	Collection: AutocompleteCollection,
	useFilter: useAutocompleteFilter,
	useFilteredItems: useAutocompleteFilteredItems,
} as const